# GCP Project & Bootstrap Configuration
create_project: true                        # Toggle to true if you want Terraform to create the project
project_id: "ankush-tf-framework-v2"           # The unique project ID (required)
project_name: "Ankush Terraform Framework"  # Display name for the GCP project
billing_account: ""                         # Associated billing account ID (required for GKE/SQL, optional for basic SA creation)
org_id: ""                                  # (Optional) Parent GCP Organization ID
folder_id: ""                               # (Optional) Parent GCP Folder ID

# APIs to automatically enable in the project
# Note: Paid APIs (like compute, container/GKE, run) require an active Billing Account linked to the project.
apis_to_enable:
  - "iam.googleapis.com"
  - "sqladmin.googleapis.com"
  # - "compute.googleapis.com"   # Requires Billing Account
  # - "container.googleapis.com" # Requires Billing Account (GKE)
  # - "run.googleapis.com"       # Requires Billing Account (Cloud Run)

# Service Account Configuration
service_account_id: "ankush-tf-sa"
service_account_display_name: "Ankush Terraform SA"
service_account_description: "Ankush Terraform SA"
service_account_roles:
  - "roles/owner"
enable_admin_roles: false
admin_roles:
  - "roles/iam.serviceAccountAdmin"
  - "roles/resourcemanager.projectIamAdmin"