# Global Variables
project_id: "binge-plus-deployment-2696"
# Service Account
service_account_id: "gcp-service-account"
service_account_display_name: "GCP Service Account"
service_account_description: "GCP Service Account"
service_account_roles:
  # - "roles/artifactregistry.admin"
  # - "roles/bigquery.dataViewer"
  # - "roles/run.viewer"
  # - "roles/cloudsql.viewer"
  - "roles/owner"
  # - "roles/compute.networkAdmin"
  # - "roles/compute.storageAdmin"
  # - "roles/compute.viewer"
  # - "roles/resourcemanager.projectIamAdmin"
  # - "roles/pubsub.viewer"
  # - "roles/iam.serviceAccountAdmin"
  # - "roles/iam.serviceAccountKeyAdmin"
  # - "roles/storage.objectAdmin"
  # - "roles/iam.serviceAccountUser"
  # - "roles/iam.serviceAccountTokenCreator"
  # - "roles/iam.serviceAccountTokenAdmin"
  # - "roles/iam.serviceAccountCredentialsAdmin"
  # - "roles/iam.serviceAccountCredentialsUser"
  # - "roles/iam.serviceAccountCredentialsTokenCreator"
  # - "roles/iam.serviceAccountCredentialsTokenAdmin"
enable_admin_roles: false
admin_roles:
  - "roles/iam.serviceAccountAdmin"
  - "roles/resourcemanager.projectIamAdmin"